API Updates
stripe/stripe-java pull request #1187
Opened 2021-02-19 21:33 UTC by richardm-stripe

Codegen for openapi 403fdb8.
r? @richardm-stripe
cc @stripe/api-libraries

## Changelog
* Added support for new resource `BillingPortal.Configuration`
* Added support for `configuration` and `on_behalf_of` on `Session#create` and `BillingPortal.Session`
* `WebhookEndpoint#create.enabled_events[]` and `WebhookEndpoint#update.enabled_events[]` added new enum members: `billing_portal.configuration.created and billing_portal.configuration.updated`

2021-02-20 01:21 UTC, remi-stripe requested changes

2021-02-20 01:21 UTC, remi-stripe commented on src/main/java/com/stripe/model/billingportal/Configuration.java
> +      public static class SubscriptionUpdateProduct extends StripeObject {
This one should be named `Product` so the client_metadata internally is wrong

2021-02-20 01:21 UTC, remi-stripe commented on src/test/java/com/stripe/functional/billingportal/ConfigurationTest.java
> +  public static final String SESSION_ID = "bps_123";
bpc_123

2021-02-20 01:21 UTC, remi-stripe commented on src/test/resources/api_fixtures/billingportal/configuration.json
> +{
We shouldn't add this. stripe-mock should have the right fixtures instead so we should remove and fix the test above

2021-02-22 14:37 UTC, richardm-stripe commented on src/test/java/com/stripe/functional/billingportal/ConfigurationTest.java
> +  public static final String SESSION_ID = "bps_123";
```suggestion
  public static final String SESSION_ID = "bpc_123";
```

2021-02-22 14:51 UTC, richardm-stripe commented
r? @remi-stripe
* Removed extra test
* SubscriptionUpdateProduct is now just Product per [latest openapi](https://github.com/stripe/openapi/commit/8887a20bdb70c5145e1e29e746e4cf7874b84997)

2021-02-22 16:39 UTC, remi-stripe approved these changes

2021-02-22 16:52 UTC, merged