API Updates: Identity APIs
stripe/stripe-java pull request #1205
Opened 2021-05-07 17:12 UTC by richardm-stripe

2021-05-07 17:31 UTC, richardm-stripe commented on src/main/java/com/stripe/model/identity/VerificationReport.java
> +    DocumentCheckError error;
Consistent with [`SigmaScheduledQuery.run_error`](https://github.com/stripe/stripe-java/blob/cbe622d4e42676e2d9c5600521f21afc6db45a01/src/main/java/com/stripe/model/sigma/ScheduledQueryRun.java#L31-L32)

2021-05-07 18:10 UTC, richardm-stripe commented on src/main/java/com/stripe/model/identity/VerificationReport.java
> +    DateOfBirth dob;
Consistent with [Individual.dob](https://github.com/stripe/stripe-java/blob/cbe622d4e42676e2d9c5600521f21afc6db45a01/src/main/java/com/stripe/model/issuing/Cardholder.java#L276-L278)

2021-05-07 23:04 UTC, remi-stripe requested changes
sending back to you based on all the things I flagged internally

2021-05-17 22:22 UTC, richardm-stripe commented on src/main/java/com/stripe/model/identity/VerificationReport.java
> +    DocumentCheckError error;
![image](https://user-images.githubusercontent.com/52928443/118563542-bd7def80-b73c-11eb-8bf3-d37c74675652.png)

2021-05-19 20:50 UTC, remi-stripe approved these changes

2021-05-19 22:32 UTC, merged