API Updates
stripe/stripe-java pull request #1329
Opened 2022-03-24 14:01 UTC by yejia-stripe

Codegen for openapi a0ffdbc.
r? @dcr-stripe
cc @stripe/api-libraries

## Changelog
* Add support for `paynow_payments` on `Account.capabilities`, `AccountCreateParams.capabilities`, and `AccountUpdateParams.capabilities`
* Add support for `failure_balance_transaction` on `Charge`
* Add support for `paynow` on `Charge.payment_method_details`, `PaymentIntent.payment_method_options`, `PaymentIntentConfirmParams.payment_method_data`, `PaymentIntentConfirmParams.payment_method_options`, `PaymentIntentCreateParams.payment_method_data`, `PaymentIntentCreateParams.payment_method_options`, `PaymentIntentUpdateParams.payment_method_data`, `PaymentIntentUpdateParams.payment_method_options`, `PaymentMethodCreateParams`, and `PaymentMethod`
* Add support for `us_bank_account` on `Charge.payment_method_details`, `Checkout.Session.payment_method_options`, `CheckoutSessionCreateParams.payment_method_options`, `Invoice.payment_settings.payment_method_options`, `InvoiceCreateParams.payment_settings.payment_method_options`, `InvoiceUpdateParams.payment_settings.payment_method_options`, `Mandate.payment_method_details`, `PaymentIntent.payment_method_options`, `PaymentIntentConfirmParams.payment_method_data`, `PaymentIntentConfirmParams.payment_method_options`, `PaymentIntentCreateParams.payment_method_data`, `PaymentIntentCreateParams.payment_method_options`, `PaymentIntentUpdateParams.payment_method_data`, `PaymentIntentUpdateParams.payment_method_options`, `PaymentMethodCreateParams`, `PaymentMethodUpdateParams`, `PaymentMethod`, `SetupAttempt.payment_method_details`, `SetupIntent.payment_method_options`, `SetupIntentConfirmParams.payment_method_options`, `SetupIntentCreateParams.payment_method_options`, `SetupIntentUpdateParams.payment_method_options`, `Subscription.payment_settings.payment_method_options`, `SubscriptionCreateParams.payment_settings.payment_method_options`, and `SubscriptionUpdateParams.payment_settings.payment_method_options`
* Add support for new values `paynow` and `us_bank_account` on enums `CheckoutSessionCreateParams.payment_method_types[]` and `PaymentMethodCreateParams.type`
* Add support for new values `paynow` and `us_bank_account` on enums `CustomerListPaymentMethodsParams.type` and `PaymentMethodListParams.type`
* Add support for new values `paynow` and `us_bank_account` on enums `InvoiceCreateParams.payment_settings.payment_method_types[]`, `InvoiceUpdateParams.payment_settings.payment_method_types[]`, `SubscriptionCreateParams.payment_settings.payment_method_types[]`, and `SubscriptionUpdateParams.payment_settings.payment_method_types[]`
* Add support for new values `paynow` and `us_bank_account` on enums `PaymentIntentConfirmParams.payment_method_data.type`, `PaymentIntentCreateParams.payment_method_data.type`, and `PaymentIntentUpdateParams.payment_method_data.type`
* Add support for `capture_method` on `PaymentIntent.payment_method_options.afterpay_clearpay`, `PaymentIntent.payment_method_options.card`, `PaymentIntent.payment_method_options.klarna`, `PaymentIntentConfirmParams.payment_method_options.afterpay_clearpay`, `PaymentIntentConfirmParams.payment_method_options.card`, `PaymentIntentConfirmParams.payment_method_options.klarna`, `PaymentIntentCreateParams.payment_method_options.afterpay_clearpay`, `PaymentIntentCreateParams.payment_method_options.card`, `PaymentIntentCreateParams.payment_method_options.klarna`, `PaymentIntentTypeSpecificPaymentMethodOptionsClient`, `PaymentIntentUpdateParams.payment_method_options.afterpay_clearpay`, `PaymentIntentUpdateParams.payment_method_options.card`, and `PaymentIntentUpdateParams.payment_method_options.klarna`
* Add support for `descriptor_code` on `PaymentIntentVerifyMicrodepositsParams` and `SetupIntentVerifyMicrodepositsParams`
* Add support for `paynow_display_qr_code` on `PaymentIntent.next_action`
* Add support for `microdeposit_type` on `PaymentIntent.next_action.verify_with_microdeposits` and `SetupIntent.next_action.verify_with_microdeposits`
* Add support for `verification_method` on `PaymentIntentTypeSpecificPaymentMethodOptionsClient` and `SetupIntentTypeSpecificPaymentMethodOptionsClient`

2022-03-24 15:19 UTC, remi-stripe requested changes

2022-03-24 15:19 UTC, remi-stripe commented on src/main/java/com/stripe/model/Mandate.java
> +  public static class UsBankAccount extends StripeObject {}
The client_metadata for that one is wrong, it should be inside `PaymentMethodDetails` like the other ones

2022-03-24 15:19 UTC, remi-stripe commented on src/main/java/com/stripe/model/SetupAttempt.java
> +    public static class UsBankAccount extends StripeObject {}
Same here, should be inside `PaymentMethodDetails`

2022-03-24 15:19 UTC, remi-stripe commented on src/main/java/com/stripe/model/Subscription.java
> +    Invoice.PaymentMethodOptions.UsBankAccount usBankAccount;
Is it expected we re-use the type here? I thought we stopped "sharing" types in java a while ago

2022-03-24 15:19 UTC, remi-stripe commented on src/main/java/com/stripe/model/Account.java
> +
you're missing `us_bank_account_ach_payments` which is part of the US Bank Account PM launch

2022-03-24 19:16 UTC, remi-stripe approved these changes

2022-03-25 19:53 UTC, dcr-stripe approved these changes
LGTM! Thanks Yejia!

2022-03-25 20:02 UTC, merged