API Updates
stripe/stripe-java pull request #1339
Opened 2022-04-14 21:43 UTC by richardm-stripe

Codegen for openapi 9e8cdc3.
r? @kamil-stripe
cc @stripe/api-libraries

## Changelog
* Change type of `FundingInstructions.bank_transfer.financial_addresses[].supported_networks[]` and `PaymentIntent.next_action.display_bank_transfer_instructions.financial_addresses[].supported_networks[]` from `literal('zengin')` to `enum('sepa'|'zengin')`
* Change type of `FundingInstructions.bank_transfer.financial_addresses[].type` and `PaymentIntent.next_action.display_bank_transfer_instructions.financial_addresses[].type` from `literal('zengin')` to `enum('iban'|'zengin')`
* Change type of `FundingInstructions.bank_transfer.type` from `literal('jp_bank_transfer')` to `enum('eu_bank_transfer'|'jp_bank_transfer')`

2022-04-14 22:57 UTC, richardm-stripe commented on src/main/java/com/stripe/model/PaymentIntent.java
> +    List<FundingInstructions.BankTransfer.FinancialAddresses> financialAddresses;
Unshare, please.

2022-04-18 18:43 UTC, dcr-stripe requested changes

2022-04-18 18:43 UTC, dcr-stripe commented on src/main/java/com/stripe/model/terminal/Configuration.java
> +  DeviceTypeSpecificConfig bbposWiseposE;
Let's unshare these.

2022-04-18 18:43 UTC, dcr-stripe commented on src/main/java/com/stripe/model/terminal/Configuration.java
> +    CurrencySpecificConfig aud;
Let's unshare these as well.

2022-04-18 18:43 UTC, dcr-stripe commented on src/test/java/com/stripe/functional/GeneratedExamples.java
> +    Customer customer = resource.createFundingInstructions(params);
We need to update this line to be `FundingInstruction fundingInstruction = ...`

2022-04-19 23:20 UTC, richardm-stripe commented
re-r? @dcr-stripe

2022-04-20 14:10 UTC, dcr-stripe approved these changes
LGTM!

2022-04-20 15:26 UTC, merged